# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  schedule:
    - cron: '30 3,14 * * *'

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
#     services:
    
#       image: nginx

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          curl 'https://me.tofly.cyou/user/checkin' \
            -X 'POST' \
            -H 'Accept: application/json, text/javascript, */*; q=0.01' \
            -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,es;q=0.7,ko;q=0.6,zh-TW;q=0.5' \
            -H 'Connection: keep-alive' \
            -H 'Content-Length: 0' \
            -H 'Cookie: uid=${{secrets.UID}}; email=dexinse%40gmail.com; key=${{secrets.KEY}}; ip=${{secrets.IP}}; expire_in=1770989956' \
            -H 'Origin: https://me.tofly.cyou' \
            -H 'Referer: https://me.tofly.cyou/user' \
            -H 'Sec-Fetch-Dest: empty' \
            -H 'Sec-Fetch-Mode: cors' \
            -H 'Sec-Fetch-Site: same-origin' \
            -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
            -H 'X-Requested-With: XMLHttpRequest' \
            -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "macOS"' \
            --compressed

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
